"""create tabel payment

Revision ID: 7cc3c5a5ecb1
Revises: d2cab90e093c
Create Date: 2023-12-14 13:24:19.390884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc3c5a5ecb1'
down_revision = 'd2cab90e093c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan',
    sa.Column('loan_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('jumlah_pinjaman', sa.Float(), nullable=False),
    sa.Column('tanggal_pinjaman', sa.DateTime(), nullable=True),
    sa.Column('tanggal_jatuh_tempo', sa.DateTime(), nullable=False),
    sa.Column('status_pinjaman', sa.String(length=50), nullable=False),
    sa.Column('bunga_pinjaman', sa.Float(), nullable=False),
    sa.Column('total_pembayaran', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('loan_id')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('loan_id', sa.BigInteger(), nullable=True),
    sa.Column('jumlah_pengembalian', sa.Float(), nullable=False),
    sa.Column('tanggal_pengembalian', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.loan_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('loan')
    # ### end Alembic commands ###
